name: Release

on: [push]

permissions:
  contents: write

jobs:

  Zip-Modern-Dark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: List Files
        run: ls ${{ github.workspace }}

      - name: Zip Stochas
        run: zip -r stochas-skins-test.zip stochas-skins

      - name: Zip Stochas
        uses: vimtor/action-zip@v1
        with:
          files: stochas-skins
          dest: stochas-skins.zip

      - name: Zip Modern Dark
        uses: vimtor/action-zip@v1
        with:
          files: surge-skins/surge-xt/modern-dark-xt.surge-skin
          dest: modern-dark.zip

      - name: Zip Modern Dark Blue
        uses: vimtor/action-zip@v1
        with:
          files: surge-skins/surge-xt/modern-dark-blue-xt.surge-skin
          dest: modern-dark-blue.zip

      - name: Zip Dark Purple
        uses: vimtor/action-zip@v1
        with:
          files: surge-skins/surge-xt/dark-purple-xt.surge-skin
          dest: dark-purple.zip

      - name: Release Notes
        run: git --no-pager log -5 --oneline --no-decorate

      - name: Release Notes
        run: git --no-pager log -5 --oneline --no-decorate > release_notes.md

      - name: Read Release Notes
        run: cat release_notes.md

      - name: List Files
        run: ls ${{ github.workspace }}

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        tag_name: Skins
        name: Surge & Stochas
        with:
          body_path: release_notes.md
          files: |
            stochas-skins.zip
            modern-dark.zip
            modern-dark-blue.zip
            dark-purple.zip
            stochas-skins-test.zip
