name: Release

on: [push]

permissions:
  contents: write

jobs:

  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Zip Stochas
        run: zip -r stochas-skins.zip stochas-skins

      - name: Zip Dark Modern
        run: zip -r modern-dark.zip surge-skins/surge-xt/modern-dark-xt.surge-skin

      - name: Zip Dark Modern Blue
        run: zip -r modern-dark-blue.zip surge-skins/surge-xt/modern-dark-blue-xt.surge-skin

      - name: Zip Dark Purple
        run: zip -r dark-purple.zip surge-skins/surge-xt/dark-purple-xt.surge-skin

      - name: Changes
        run: echo -e "Changes:\n" > changes.md

      - name: Git Log
        run: git --no-pager log -5 --oneline --no-decorate >> changes.md

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: latest
          name: Downloads
          body_path: changes.md
          files: |
            stochas-skins.zip
            modern-dark.zip
            modern-dark-blue.zip
            dark-purple.zip
