name: Release

on: [push]

permissions:
  contents: write

jobs:

  SVGO:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SVGO
        run: cd surge-skins/surge-xt/ && ls && npx svgo */SVG && cd ../ && ls

      - name: Git credential
        run: git config --global user.email "mthierman@gmail.com" && git config --global user.name "Mike Thierman"

      - name: Git
        run: git commit -am 'SVGO Compression' && git push

  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: SVGO
        run: cd surge-skins/surge-xt/ && ls && npx svgo */SVG && cd ../../ && ls

      - name: Git credential
        run: git config --global user.email "mthierman@gmail.com" && git config --global user.name "Mike Thierman"

      - name: Git
        run: git commit -am 'SVGO Compression' || true && git push

      - name: Zip Stochas
        run: zip -r stochas-skins.zip stochas-skins

      - name: Zip Skins
        run: cd surge-skins/surge-xt/; for i in *; do zip -r "$i.zip" $i; done;

      - name: Changes
        run: echo -e "Changes:\n" > changes.md && git --no-pager log -5 --oneline --no-decorate >> changes.md

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: latest
          name: Latest
          body_path: changes.md
          files: |
            *.zip
            surge-skins/surge-xt/*.zip
