name: SVGO

on: workflow_dispatch

permissions:
  contents: write

jobs:

  Test2:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: SVGO
        run: cd surge-skins/surge-xt/ && npx svgo */SVG && cd ../

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: skins
          path: surge-xt/*
