name: SVGO

on: workflow_dispatch

permissions:
  contents: write

jobs:

  Test2:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: SVGO
        run: cd surge-skins/surge-xt/ && ls && npx svgo */SVG && cd ../ && ls

      - name: Git
        run: git add . && git commit -m 'SVGO Compression'
