name: Zip Files

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:

  Zip-Modern-Dark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: modern-dark
          path: surge-skins/surge-xt/modern-dark-xt.surge-skin
      - name: Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "modern-dark"
          token: ${{ secrets.GITHUB_TOKEN }}
