name: Zip Files

on: [push]

jobs:

  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  Zip-Modern-Dark:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: ls
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: modern-dark
          path: surge-skins/surge-skins/surge-xt/modern-dark-xt.surge-skin

  Zip-Modern-Dark-Blue:
    runs-on: ubuntu-latest
    steps:
      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          files: surge-skins/surge-xt/modern-dark-blue-xt.surge-skin
          dest: skins/modern-dark-blue.zip

  Zip-Modern-Dark-Purple:
    runs-on: ubuntu-latest
    steps:
      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          files: surge-skins/surge-xt/dark-purple-xt.surge-skin
          dest: skins/dark-purple.zip
