name: Zip Files

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:

  Zip-Modern-Dark:
    runs-on: ubuntu-latest
    steps:
      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          files: surge-skins/surge-xt/modern-dark-xt.surge-skin
          dest: modern-dark.zip
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: modern-dark.zip
