name: Zip Files

on: [push]

jobs:

  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  Zip-Modern-Dark:
    runs-on: ubuntu-latest
    steps:
      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          files: surge-skins/surge-xt/modern-dark-xt.surge-skin
          dest: modern-dark.zip

  Zip-Modern-Dark-Blue:
    runs-on: ubuntu-latest
    steps:
      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          files: surge-skins/surge-xt/modern-dark-blue-xt.surge-skin
          dest: modern-dark-blue.zip

  Zip-Modern-Dark-Purple:
    runs-on: ubuntu-latest
    steps:
      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          files: surge-skins/surge-xt/dark-purple-xt.surge-skin
          dest: dark-purple.zip
